"""Application policy constants. Edit here; do not hide them inside Jev."""

CHOICE_MAX_OPTIONS = 255
FIND_CHUNK = 255
RANK_CHUNK = 64

FIND_EXISTS_ANSWERED = 0.70
FIND_EXISTS_PARTIAL = 0.35

VERIFY_AUTO_CONFIDENCE = 0.80

NOUL_UNCERTAIN_LOW = 0.30
NOUL_UNCERTAIN_HIGH = 0.70
CHOICE_MIN_TOP_P = 0.60

SCREEN_JAILBREAK = 0.70
SCREEN_INJECTION = 0.70
SCREEN_SENSITIVE = 0.70
SCREEN_HARM_REVIEW = 1.5

SKILL_TOP_K = 3
SKILL_NEEDS_MIN = 0.55
SKILL_FITS_MIN = 0.55
SKILL_EXCERPT_CHARS = 1200
